### ISSUE TITLE
Exception executing last step of Forge Richfaces install

### ISSUE THREAD

**Issue by matteg** [richfaces/richfaces-forge-plugin#8]
Following the instructions for the Richfaces add-on for Forge, I encountered an exception on the last step richfaces-facelet :

D:\Gerry\Documents\$develop\$code>forge
Using Forge at C:\s\jboss-forge-3.6.1.Final

    _____
   |  ___|__  _ __ __ _  ___
   | |_ / _ \| `__/ _` |/ _ \  \\
   |  _| (_) | | | (_| |  __/  //
   |_|  \___/|_|  \__, |\___|
                   |__/

JBoss Forge, version [ 3.6.1.Final ] - JBoss, by Red Hat, Inc. [ http://forge.jboss.org ]
Hit '<TAB>' for a list of available commands and 'man [cmd]' for help on a specific command.

To quit the shell, type 'exit'.

[$code]$ addon-install-from-git --url https://github.com/richfaces/richfaces-forge-plugin.git;
***INFO*** Installing Addon from Git    [1/4] ...
***INFO*** Installing Addon from Git:Cloning repository in C:\Users\Gerry\AppData\Local\Temp\tmpdir5388579248901701145  [1/4] ...
***INFO*** Installing Addon from Git:Installing project into local repository   [2/4] ...
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.richfaces.forge:richfaces-forge-addon:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 79, column 18
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building richfaces-forge-addon 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ richfaces-forge-addon ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ richfaces-forge-addon ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ richfaces-forge-addon ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 5 source files to C:\Users\Gerry\AppData\Local\Temp\tmpdir5388579248901701145\target\classes
[WARNING] /C:/Users/Gerry/AppData/Local/Temp/tmpdir5388579248901701145/src/main/java/org/richfaces/forge/RichFacesFacetImpl.java: C:\Users\Gerry\AppData\Local\Temp\tmpdir5388579248901701145\
src\main\java\org\richfaces\forge\RichFacesFacetImpl.java uses unchecked or unsafe operations.
[WARNING] /C:/Users/Gerry/AppData/Local/Temp/tmpdir5388579248901701145/src/main/java/org/richfaces/forge/RichFacesFacetImpl.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ richfaces-forge-addon ---
[INFO] Not copying test resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ richfaces-forge-addon ---
[INFO] Not compiling test sources
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ richfaces-forge-addon ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ richfaces-forge-addon ---
[INFO] Building jar: C:\Users\Gerry\AppData\Local\Temp\tmpdir5388579248901701145\target\richfaces-forge-addon-2.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (create-forge-addon) @ richfaces-forge-addon ---
[INFO] Building jar: C:\Users\Gerry\AppData\Local\Temp\tmpdir5388579248901701145\target\richfaces-forge-addon-2.0.0-SNAPSHOT-forge-addon.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ richfaces-forge-addon ---
[INFO] Installing C:\Users\Gerry\AppData\Local\Temp\tmpdir5388579248901701145\target\richfaces-forge-addon-2.0.0-SNAPSHOT.jar to d:\d\mavenLocalRepository\org\richfaces\forge\richfaces-forge
-addon\2.0.0-SNAPSHOT\richfaces-forge-addon-2.0.0-SNAPSHOT.jar
[INFO] Installing C:\Users\Gerry\AppData\Local\Temp\tmpdir5388579248901701145\pom.xml to d:\d\mavenLocalRepository\org\richfaces\forge\richfaces-forge-addon\2.0.0-SNAPSHOT\richfaces-forge-ad
don-2.0.0-SNAPSHOT.pom
[INFO] Installing C:\Users\Gerry\AppData\Local\Temp\tmpdir5388579248901701145\target\richfaces-forge-addon-2.0.0-SNAPSHOT-forge-addon.jar to d:\d\mavenLocalRepository\org\richfaces\forge\ric
hfaces-forge-addon\2.0.0-SNAPSHOT\richfaces-forge-addon-2.0.0-SNAPSHOT-forge-addon.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.749 s
[INFO] Finished at: 2017-05-15T17:19:30-07:00
[INFO] Final Memory: 42M/102M
[INFO] ------------------------------------------------------------------------
***INFO*** Installing Addon from Git:Removing previous addon installation (org.richfaces.forge:richfaces-forge-addon,2.0.0-SNAPSHOT)    [3/4] ...
***INFO*** Installing Addon from Git:Installing addon (org.richfaces.forge:richfaces-forge-addon,2.0.0-SNAPSHOT)        [4/4] ...
***SUCCESS*** Addon(s) [org.richfaces.forge:richfaces-forge-addon,2.0.0-SNAPSHOT] installed successfully.
[$code]$ project-new --named finance --topLevelPackage ca.gerrymatte.finance --type war --finalName finance ;
***SUCCESS*** Project named 'finance' has been created.
[finance]$ servlet-setup;
***SUCCESS*** Servlet API has been installed.
[finance]$ faces-setup --facesVersion 2.2;
***SUCCESS*** JavaServer Faces has been installed.
[finance]$ richfaces-setup
***SUCCESS*** Installed RichFaces RICHFACES_4_5_0
[finance]$ richfaces-facelet
***ERROR*** Error while executing 'RichFaces: Facelet'
***INFO*** (type "export VERBOSE=true" to enable stack traces)
[finance]$ export VERBOSE=true
[finance]$ richfaces-facelet
***ERROR*** Error while executing 'RichFaces: Facelet'
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
        at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
        at org.richfaces.forge.RichFacesInstallFaceletCommand_$$_javassist_ebf502ec-4936-430d-81fb-b86de417319b.execute(RichFacesInstallFaceletCommand_$$_javassist_ebf502ec-4936-430d-81fb-b8
6de417319b.java)
        at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.execute(SingleCommandControllerImpl.java:94)
        at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:97)
        at org.jboss.forge.addon.shell.aesh.ForgeCommandContainer.executeCommand(ForgeCommandContainer.java:88)
        at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:311)
        at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.jboss.forge.addon.ui.result.Results.fail(Ljava/lang/String;)Lorg/jboss/forge/addon/ui/result/Result;
        at org.richfaces.forge.RichFacesInstallFaceletCommand.execute(RichFacesInstallFaceletCommand.java:35)
        ... 16 more
[finance]$

**Comment by michpetrov** [comment]
The plugin was created for 2.10.1, if it doesn't work with 3.6.1 that's unfortunate but kind of expected. RichFaces has reached end-of-life, so this is not going to get fixed, at least not by me.

**Comment by matteg** [comment]
That's too bad.  Richfaces is a mature technology and I can understand why jboss declared it was at end of life for them.  Even though they've chosen to not work on new development of Richfaces they do still fix bugs ... particularly security related.

If society in general chose to treat their seniors as being "end of life" I'm guessing their would be no more health care or social benefits for seniors like me ......
